sonar.projectKey=MINDU

sonar.projectName=MINDU

sonar.sources=src/main/java

sonar.java.binaries=target/classes

sonar.host.url=http://localhost:9000

sonar.token=sqp_3c4fed0ea2bec53311a29bfc69fe02f5f9aafdb6